### ISSUE TITLE
Recent XP should disregard top languages

### ISSUE THREAD

**Issue by aksh1618** [aksh1618/codestats-box-python#2]
The recent xp mode currently just adds the (+ xp) part to the overall top languages if new xp is present. It should instead show top languages by new xp instead of by total xp. This should be made the behaviour for current Recent XP mode, complete with the level, as shown on the official codestats site:
```
Rust ::::::::::::::::::: lvl 0 (1,289 XP) (+10)
```
The current behaviour of recent xp mode could be moved to a new mode, or removed entirely.

**Comment by paveloom** [comment]
That's exactly what I am looking for. Would be happy to see this implemented.

**Comment by sciencepal** [comment]
@aksh1618 should I take this up .. seems like an easy change :P

**Comment by aksh1618** [comment]
@sciencepal I have already have this WIP but didn't finish due to a busy week :sweat_smile: Would push tomorrow!

**Comment by aksh1618** [comment]
Essentially what's left is deciding what to do when there aren't enough _recent-xp_ languages to fill the list. 
- Should it be left with less rows (which might work as a challenge for the user :smile:)
- Should it default to filling with _highest-total-xp_ languages after the _highest-recent-xp_ ones (which might look a bit weird formatting & sorting-wise). 

I'm leaning towards the former, but suggestions welcome! @Paveloom @sciencepal  @karngyan

**Comment by paveloom** [comment]
Well, I'm for honesty. If I haven't worked for a week, let it be honestly reflected in my stats: `Total XP` and `No new XP in the last week`. This makes sense also because this type of statistic is intentionally called `recent-xp`.
